services:
  redis:
    image: redis:7
    ports:
    - 6379:6379
    networks:
    - test
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    hostname: rediscommander
    networks:
    - test
  whoami:
    image: traefik/whoami
    networks:
    - test
networks:
  test:
    external: true