# Example Wikibase docker-compose setup
version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: ${MW_ADMIN_NAME}
  MW_ADMIN_PASS: ${MW_ADMIN_PASS}
  MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
  MW_WG_SECRET_KEY: ${MW_SECRET_KEY}
  # Disable jobs running after requests when wikibase_jobrunner is defined
  MW_WG_JOB_RUN_RATE: 0
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_NAME: ${DB_NAME}
  WIKIBASE_HOST: ${WIKIBASE_HOST}
  QS_PUBLIC_SCHEME_HOST_AND_PORT: http://${QUICKSTATEMENTS_HOST}:${QUICKSTATEMENTS_PORT}

services:
  wikibase:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    #build: ./mediawiki
    container_name: mardi-wikibase
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${WIKIBASE_PORT}:80"
    volumes:
      ## This shares the configuration with jobrunner
      - shared:/var/www/html/:rw
      - ./mediawiki/LocalSettings.override.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
      - ./mediawiki/images/MaRDI_Logo.png:/var/www/html/images/MaRDI_Logo.png
      - ./mediawiki/images/favicon.png:/var/www/html/images/favicon.png
      - ./mediawiki/extensions/JsonConfig:/var/www/html/extensions/JsonConfig
      - ./mediawiki/extensions/TemplateStyles:/var/www/html/extensions/TemplateStyles
      - ./mediawiki/extensions/Math:/var/www/html/extensions/Math
      - ./mediawiki/extensions/MathSearch:/var/www/html/extensions/MathSearch
    networks:
      default:
        aliases:
         - ${WIKIBASE_HOST}
         - wikibase-docker.svc
    environment:
      <<: *wikibase_variables
      WIKIBASE_PINGBACK:
      MW_WG_ENABLE_UPLOADS:

  wikibase_jobrunner:
    image: "${WIKIBASE_BUNDLE_IMAGE_NAME}"
    entrypoint: /bin/bash
    command:  /jobrunner-entrypoint.sh
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    volumes:
      - shared:/shared/:ro
      - ./mediawiki/jobrunner-entrypoint.sh:/jobrunner-entrypoint.sh
    networks:
      default:
        aliases:
          - wikibase-jobrunner.svc
    environment:
      <<: *wikibase_variables
      MAX_JOBS: ${MAX_JOBS}

  mysql:
    image: "${MYSQL_IMAGE_NAME}"
    container_name: mardi-mysql
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc

  reverse-proxy:
    restart: always
    image: traefik:v2.5
    ports:
      - 443:443 # HTTPS port
      - 80:80 # HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/conf/:/traefik-conf/:ro
      - traefik-letsencrypt:/letsencrypt # Persistent file for ACME Setup (Certificate Store)
      - traefik-log:/data/log # Persistent file for logging
    networks:
     - default
     - wdqs
    labels:
      - traefik.enable=false
  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    restart: always
    
  selenium:
    image: aot29/selenium
    container_name: mardi-selenium
    volumes:
      - ./test:/test

volumes:
  shared:
  mediawiki-mysql-data:
  traefik-log:
  traefik-letsencrypt:
networks:
    wdqs:
