version: '3.4'

x-common-variables: &wikibase_variables
    WIKIBASE_HOST: localhost
    WIKIBASE_PORT: 8080    
    WDQS_FRONTEND_PORT: 8834
    QUICKSTATEMENTS_HOST: localhost
    QUICKSTATEMENTS_PORT: 8840
    # required by quickstatements for creating OAuth consumers,
    # and by wikibase for redirecting back to quickstatements
    QS_PUBLIC_SCHEME_HOST_AND_PORT: 'http://${QUICKSTATEMENTS_HOST}:${QUICKSTATEMENTS_PORT}'
    WB_PUBLIC_SCHEME_HOST_AND_PORT: 'http://${WIKIBASE_HOST}:${WIKIBASE_PORT}'
    
services:
  wikibase:
    ports:
      - "${WIKIBASE_PORT}:80"
    restart: 'no'
    environment:
      <<: *wikibase_variables

  wikibase_jobrunner:
    restart: 'no'

  mysql:
    restart: 'no'

  wdqs-frontend:
    ports:
     - "${WDQS_FRONTEND_PORT}:80"
    restart: 'no'

  quickstatements:
    ports:
      - "${QUICKSTATEMENTS_PORT}:80"
    restart: 'no'
    environment:
      <<: *wikibase_variables

  backup:
    restart: 'no'
    volumes:
      # only for running tests
      - ./test:/test

  reverse-proxy:
    restart: 'no'

  whoami:
    restart: 'no'

  elasticsearch:
    restart: 'no'

  wdqs:
    restart: 'no'

  wdqs-proxy:
    restart: 'no'

  wdqs-updater:
    restart: 'no'
    
  portainer:
    restart: 'no'
    
  selenium:
    image: aot29/selenium
    restart: 'no'
    container_name: mardi-selenium
    volumes:
      - ./test:/test

  openrefine:
    image: ghcr.io/aot29/docker-openrefine:master
    restart: 'no'
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data
    environment:
      - REFINE_INTERFACE=0.0.0.0
      - REFINE_PORT=3333
      - REFINE_MEMORY=1024M
      - REFINE_DATA_DIR=/data
