http:
  routers:
    home:
      rule: Host(`whoami.mardi.schubotz.org`,`whoami.mardi.formulasearchengine.com`)
      service: whoami-docker@docker
      entryPoints: [websecure]
      tls:
        certResolver: le
