log:
  level: DEBUG

accessLog:
  filePath: "/data/log/access.log"

api:
  dashboard: true

entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":80"
      # redirect to https
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https

providers:
  docker: {}

certificatesResolvers:
  le:
    acme:
      tlschallenge: true
      storage: /letsencrypt/acme.json
      email: ssl-mardi01@ckurs.de
      httpChallenge:
        # used during the challenge
        entryPoint: web
