name: wb docker-compose-actions-workflow
on: 
  push:
    branches: 
      - 'main'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      -
        name: Prepare the build
        run: cp mediawiki/template.env ./.env

      - 
        name: Build the stack
        env:
          MW_ADMIN_PASS: ${{ secrets.MW_ADMIN_PASS }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: 
          MW_ADMIN_PASS=${{ secrets.MW_ADMIN_PASS }} DB_PASS=${{ secrets.DB_PASS }} docker-compose up -d
          
      # pauses CI execution and prints a temporary ssh url to the server for debugging
      #-
      #  name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3 
           
      - 
        name: Give docker compose time to start
        run: sleep 10
        # actually, it would be better to have the selenium container wait for the other containers
 
      -
        name: Test using Selenium
        run: docker exec mardi-selenium bash -c "export MW_ADMIN_PASS=${{ secrets.MW_ADMIN_PASS }} && ./start_test_runner.sh test"
