name: wb docker-stack-actions-workflow
on: 
  push:
    branches: 
      - 'main'
  pull_request:
  schedule:
    - cron: '30 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build the stack
        run: >
          docker swarm init &&
          docker network create --driver=overlay --attachable test
      - 
        name: Show the networks
        run: docker network ls
      - 
        name: Deploy the stack
        run: docker stack deploy mardistack --compose-file docker-compose-stack.yml 