name: wb docker-compose-actions-workflow
on: 
  push:
    branches: 
      - 'main'
  pull_request:
  schedule:
    - cron: '30 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build the stack
        env:
          MW_ADMIN_PASS: ${{ secrets.MW_ADMIN_PASS }}
          DB_PASS: ${{ secrets.DB_PASS }}
          WIKIBASE_HOST: ${{ secrets.WIKIBASE_HOST}}
          WIKIBASE_PORT: ${{ secrets.WIKIBASE_PORT}}
          WDQS_FRONTEND_HOST: ${{ secrets.WDQS_FRONTEND_HOST}}
          WDQS_FRONTEND_PORT: ${{ secrets.WDQS_FRONTEND_PORT}}
          QUICKSTATEMENTS_HOST: ${{ secrets.QUICKSTATEMENTS_HOST}}
          QUICKSTATEMENTS_PORT: ${{ secrets.QUICKSTATEMENTS_PORT}}
          WB_PUBLIC_HOST_AND_PORT: ${{ secrets.WB_PUBLIC_HOST_AND_PORT}}
          QS_PUBLIC_HOST_AND_PORT: ${{ secrets.QS_PUBLIC_HOST_AND_PORT}}
        run: >
          MW_ADMIN_PASS=${{ secrets.MW_ADMIN_PASS }} 
          DB_PASS=${{ secrets.DB_PASS }} 
          docker stack deploy --compose-file docker-compose-stack.yml mardistack 
